# Generated by Django 4.2.3 on 2023-07-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogonit', '0008_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click above to read', max_length=255),
        ),
    ]
